### ISSUE TITLE
Payload Sender Windows?

### ISSUE THREAD

**Issue by seanp2500** [valentinbreiz/PS4-Payload-Sender#1]
Hi.  Is this app only for Linux?  I don't see an exe and I am kinda puzzled how I would load this?

**Comment by valentinbreiz** [comment]
It's for Windows you can download it here: https://github.com/valentinbreiz/PS4-Payload-Sender/releases/download/1.1/PS4.Payload.Sender.exe

**Comment by seanp2500** [comment]
does not connect.  Netcat gui works fine.  Also.

I cannot get the darbness site to fully load.  I can inject payload via netcat gui but nothing happens just whitescreen.  I can host a private video to show you what happens on my end.  I am in windows 10.  I figured try your app but then I get connection refused (both lan and internet) but netcar port 9020 work fine is there a certain port I need to use (sorry if explained elsewhere)

**Comment by seanp2500** [comment]
GOT EVERYTHING WORKING WITH Al Azif files so sorry I bothered you sir thank you for your work any tips to port xmugen?
